#!/bin/bash

function fail {
    if [[ $# -lt 2 ]]
    then
        echo "The fail function requires a failure string and an error code"
        exit 1
    fi
    echo $1
    exit $2
}

function image_exists {
    if [[ $# -lt 1 ]]
    then
        echo "The image_exists function requires the name of an image"
        exit 1
    fi
    docker image inspect ${name} &> /dev/null
    return $?
}
